marl:
  general:
    data_dir: data/20250930_223742
    climate_engine: net
    training_run_id: 20260307_174513_gru_128_1
    marl_run_name: heterogenous_agents
    log_episode_trajectories: True       # master ON/OFF switch
    log_dir: None #marl_logs             # where to save .npz files (optional; set None to skip saving to disk)
    surrogate_device: cuda
    surrogate_autocast: false
    surrogate_use_half: false
    random_seed: 2
  environment:
    num_agents: 4
    country_names: ["Germany", "Poland", "Spain", "Sweden"]
    use_empirical_damage: true
    damage_seed: 0
    baseline_emission_shares: [0.53, 0.26, 0.18, 0.03] # Note: Normalized actual shares; [0.2753, 0.1330, 0.0957, 0.0166]
    horizon: 35
    rollout_length: 15
  economics:
    costs: # Note: Same costs across all agents (but individual policy matrices)
      climate_damage_costs: [1000.0, 1000.0, 1000.0, 1000.0]
      energy_costs: [0.081, 0.081, 0.081, 0.081]
      methane_costs: [0.075, 0.075, 0.075, 0.075]
      agriculture_costs: [0.147, 0.147, 0.147, 0.147]
      adaptation_costs: [0.697, 0.697, 0.697, 0.697]
    prevention_decay: 0.95
    max_prevention_benefit: 0.5 # Note: Using max prevention benefit instead of emission reductions from the country-level climate models
  actions:
    energy_levels: [0.0, 0.5, 1.0]
    methane_levels: [0.0, 0.5, 1.0]
    agri_levels: [0.0, 0.5, 1.0]
    adaptation_levels: [0.0, 0.03, 0.08]
    policy_matrix: # Germany, Poland, Spain, Sweden
      energy:
        CO2_FF: [-0.0033, -0.0045, -0.008, -0.0122]
      methane:
        CO2_FF: [-0.0154, -0.0062, -0.0028, -0.0004]
      agriculture:
        CO2_FF: [-0.0013, 0, -0.0004, -0.0001] # Note: Ignoring positive CO2 effect for Poland
  training:
    num_iterations: 500
    greedy_eval_interval: 2
    output_dir: marl_results
    seed: 42
    ppo:
      framework: torch
      model:
        use_lstm: true
        lstm_cell_size: 128
        vf_share_layers: false
      train_batch_multiplier: 8
      minibatch_multiplier: 2
      num_epochs: 5
      gamma: 0.999
      lr: 0.0002
      lr_schedule:
        - [0,        0.0002]
        - [100000,   0.0001]
        - [350000,   0.00005]
        - [750000,   0.00003]
        - [1250000,  0.00001]
      clip_param: 0.3
      entropy_coeff: 0.02
      entropy_coeff_schedule:
        - [0,        0.02]
        - [150000,   0.01]
        - [500000,   0.005]
        - [800000,   0.003]
        - [1400000,  0.0001]
        - [1800000,  0.00001]
      rollout:
        num_env_runners: 1
        num_envs_per_runner: 32
        fragment_length: auto
        num_gpus_per_env_runner: 1
        sample_timeout_s: 1200
      resources:
        num_gpus: 1